src/decoder.rs

Hey there! Amazing work with this crate :D
Since `read_ipv4` will refuse any length different than four, I don't see why we couldn't use the const generics-backed `read` function

Use `Decoder::read` in `read_ipv4`

---

Cargo.lock
Cargo.toml
README.md
src/v4/mod.rs
src/v6/mod.rs
src/v6/options.rs

closes #2 
We could obviously use more docs, but this gets us started with some examples.
We were missing some public constructor methods for `v6::Message`, added those also/clarify which bytes get copied for xid.

module examples & v6 methods

---

src/decoder.rs
src/encoder.rs
src/v4/mod.rs

closes #3 
It does break the API slightly, however I don't expect this to happen much in the future and I think it's preferable to adding `_bytes` or `_raw` methods to the `Message` type.

switch to using bytes for sname/fname

---

src/decoder.rs

Replacing the cursor with split_at removes the addition operations from all reads, which removes the overflow check and error return path. The remaining overflow case is only where the index is out of bounds anyway, so we don't care.
This is almost the same patch that I sent to trust-dns some time ago: https://github.com/bluejekyll/trust-dns/pull/1399/files
The only potential problem is that `DecodeError::EndOfBuffer` is no longer constructed by this crate, because this PR removes the information required to construct it.
Here's my before-and-after criterion:
```
decode/decode_offer     time:   [687.25 ns 687.60 ns 687.96 ns]
change: [-15.317% -15.244% -15.169%] (p = 0.00 < 0.05)
Performance has improved.
decode/decode_bootreq   time:   [118.94 ns 119.04 ns 119.14 ns]
change: [-18.150% …
```

Replace Decoder's cursor with split_at, 10-18% opt

---

Cargo.lock
Cargo.toml
src/v4/options.rs

Adds `SubnetSelection` to dhcp options. I considered adding `#[non_exhaustive]` to the various opt enums so future additions wouldn't be a breaking change. But I think the likelihood that users are exhaustively matching on it is low, most probably just use `msg.opts().get(OptionCode::Blah)`

add subnetselection opt

---

src/v4/flags.rs
src/v4/options.rs
src/v4/relay.rs

Had to engage with relay options today and realized that methods were not made public to actually interact with it. `Info` was not ever actually accessible AFAICT. 
Relay agent sub-options work similarly to the upper level dhcp options, just sitting inside opt 82. This implementation borrows a lot of the same code for that, I've skipped some opts that were just too onerous to figure out for now, those will be decoded into the `UnknownInfo` variant and the bytes can be pulled out that way.

finer grained relay agent info

---

src/v4/options.rs
src/v4/relay.rs
src/v6/options.rs

erase concrete iterator types in favor of `impl Iterator`

erase iterator from opts/relayinfo

---

.github/workflows/actions.yml
CHANGELOG
Cargo.lock
Cargo.toml

Added previous changes/fixes to `CHANGELOG`, cut 0.5.0 release. The variant brokenness for `DhcpOption` needs to go out

0.5.0 & add to changelog

---

src/v4/mod.rs

Current `set_chaddr()` function expects a `[u8;16]` slice due to
requirement of `copy_from_slice()`. This cause the `hlen` been always
set to 16.
This patch fix it by allowing variable length of input u8 slice and set
`hlen` accordingly.
Tested in my person project with dnsmasq:
* Before:
`DHCPREQUEST(eth1.ep) 192.0.2.32`
`12:a9:63:e8:f0:b8:00:00:00:00:00:00:00:00:00:00`
* After:
`DHCPREQUEST(eth1.ep) 192.0.2.32 12:a9:63:e8:f0:b8`

set_chaddr: Fix the hardware setting

---

CHANGELOG
src/v4/mod.rs

Add a test for the `set_chaddr` fix & add it to the changelog.

dhcpv4: CHANGELOG & test set_chaddr

---

Cargo.lock
Cargo.toml
src/v4/flags.rs
src/v4/htype.rs
src/v4/mod.rs
src/v4/opcode.rs
src/v4/options.rs
src/v4/relay.rs
src/v6/mod.rs
src/v6/options.rs

I thought it might be valuable to encode these types as JSON, say for logging purposes. I added an optional feature `"serde"` that when enabled, allows the types to be encoded/decoded using `serde`

Impl serde optionally for types

---

CHANGELOG
Cargo.lock
Cargo.toml
src/error.rs
src/v4/options.rs

Add opt 119 for v4, uses `trust_dns_proto`'s `Name` type for domain decoding/encoding.
https://www.rfc-editor.org/rfc/rfc3397.html

v4: add opt 119

---

src/decoder.rs
src/v4/flags.rs
src/v4/htype.rs
src/v4/mod.rs
src/v4/opcode.rs
src/v4/options.rs
src/v4/relay.rs
src/v6/mod.rs
src/v6/options.rs

Moving the lifetime into Decodable makes it much more restrictive when actually using `<'a, T: Decodable<'a>`. `Opt` is an internal type so it doesn't _need_ to implement the trait.

make opt not impl Decodable

---

CHANGELOG
Cargo.lock
Cargo.toml
src/v4/options.rs

relay agent information is supposed to be added
at the end of the buffer. So, in `encode` if it is
present we filter it out and add it at the end

v4: add relay opt at end of opts

---

CHANGELOG
src/v4/options.rs
src/v6/mod.rs
src/v6/options.rs

Duplicates are allowed in the v6 options list. I considered changing the representation to `HashMap<_, Vec<_>>` or even `SmallVec<[_; 1]>`. Hard to know without benchmarks what would be better.
At the moment, I thought that duplicates would be rare, so an extra alloc per insert is probably not worth it. `SmallVec` would keep things on the stack but without a benchmark it feels premature. I opted instead to just leave it as a list and maintain sorted state internally.

v6: sorted DhcpOptions

---

Cargo.lock
Cargo.toml
src/error.rs
src/v4/options.rs

This PR adds support for DHCP option 121 (Classless Static Routes) for DHCPv4 as described in RFC3442.
This option allows a DHCP server to send a whole routing table to a client. It is also sometimes used instead of DHCP option 3 (Router) in some environments.
Related to this option, this PR adds support for merging some consecutive DHCP options that contains lists of items, option 121 being a prime example. The previous behavior was to replace the previously parsed option when encountering it multiple times in a packet; however it may be useful to specify options multiple times when they are pretty large (e.g. large routing tables).

v4: add option 121

---

CHANGELOG.md
src/v4/mod.rs

It's possible to call `set_fname(b"")` but that will represent the `Message` field as `Some([])` rather than `None`. The generated packet will be the same but may as well just provide these methods.

v4: adds methods to clear sname/fname

---

src/decoder.rs
src/v4/bulk_query.rs
src/v4/flags.rs
src/v4/fqdn.rs
src/v4/options.rs
src/v4/relay.rs
src/v6/options.rs

Adds some convenience methods to client fqdn. The `FqdnFlags` didn't have a way to turn off either without just recreating the flag set, so the methods have been changed to toggle `set_x` and take `true`/`false`.

Client FQDN

---

src/v6/options.rs

When the `DhcpOptions` struct has nothing in it, the code panics (in debug mode) due to an underflowing substraction (`len - 1`), or wraps and takes ages in release mode. This can happen when getting suboptions of options. My case:
```rust
let msg: dhcproto::v6::Message = .......;
if let Some(DhcpOption::IANA(IANA { id, opts, ... })) = msg.opts().get(OptionCode::IANA) {
if let Some(DhcpOption::IAAddr(addr)) = opts.get(OptionCode::IAAddr) { // .get panics
//
}
}
```
This crashes using `dhclient -6` with the following stacktrace:
```
thread 'main' panicked at 'attempt to subtract with overflow', /home/tuetuopay/.cargo/git/checkouts/dhcproto-5f8e80f362f839f6/406cd43/src/v6/options.rs:822:17
stack backtrace:
0: rust_begin_unwind
at ./rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/s …
```

fix(dhcpv6): fix panic when accessing empty DhcpOptions

---

src/v6/options.rs

When trying to get a non-existent option code from the DhcpOptions struct, the code panics due to an underflowing substraction.

fix(dhcpv6): fix panic when accessing a missing option

---

src/decoder.rs
src/v4/relay.rs

During decoding agent remote id(2) in option82, instead of returning AgentRemoteId, AgentCircuitId is returned. This fix returns AgentRemoteId after decoding it.

Return AgentRemoteId after decoding, instead of AgentCircuitId

---

src/v4/htype.rs
src/v6/duid.rs
src/v6/htype.rs
src/v6/mod.rs

Hello! I referred to the implementation of v4 htype and added support for v6 htype extended to u16. The following content includes:
(1) Add v6 support. I added the code for v6 htype under the v6 folder, most of which is the same as the code for v4 htype, which may be redundant. Is there a better solution?
(2) For the original v4 htype, I referred to https://www.iana.org/assignments/arp-parameters/arp-parameters.xhtml and made some supplements, and my questions can be found in #68.

modify v6 Htype

---

src/v6/option_codes.rs
src/v6/options.rs

Hello 😄,
I'm trying to implement NTP server advertisement via dhcpv6 server created from this lib but the option is not officially supported.
Here's an implementation of the NTP option for dhcpv6.

feat(dhcp6): implement `NTP_SERVER` options

---

src/encoder.rs

This PR adds two methods to the `Encoder`:
- `buffer_filled`: returns only the portion of the buffer that was written to, i.e. the serialized message.
- `len_filled`: returns the number of bytes that have been written.
In my usecase I'm reusing a buffer for sending/receiving. I don't want to truncate the buffer to length 0, just to have to grow (and thus initialize) it later again. `Encoder` writes to the buffer from the beginning anyway and only grows it as needed. If the buffer was larger that the serialized message, the `buffer()` method will still return the whole buffer, including any garbage at the end of the buffer.
With `buffer_filled` and `len_filled` you can easily get a slice of the serialized message.

`Encoder::buffer_filled` and `::len_filled`

---

src/v4/mod.rs

One of our applications that is using this library ran into a panic:
```
panicked at /Users/andrew/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/dhcproto-0.13.0/src/v4/mod.rs:286:21:
range end index 21 out of range for slice of length 16
```
Looking at the code, I think I see why. In the case where `chaddr`s length is greater than 16 and the `new_chaddr` is chunked to just 16 characters, the `hlen` is still being set to `chaddr`s length, which is possibly greater than 16 characters. I think that `hlen` should also be set to 16 in this case.

Adjust hlen for case where chaddr length is greater than 16.
